kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  - containerPort: 5000
    hostPort: 5000
    listenAddress: "127.0.0.1"
  - containerPort: 8080
    hostPort: 8080
  - containerPort: 8090
    hostPort: 8090
  - containerPort: 8001
    hostPort: 8001
  extraMounts:
  - hostPath: E:\PodmanDrive
    containerPath: /data
- role: worker
  extraMounts:
  - hostPath: E:\PodmanDrive
    containerPath: /data