kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 8080
    hostPort: 5000
    listenAddress: "127.0.0.1"
    protocol: TCP
  - containerPort: 6379
    hostPort: 5001
    listenAddress: "127.0.0.1"  
    protocol: TCP
  - containerPort: 8001
    hostPort: 5002
    listenAddress: "127.0.0.1"
    protocol: TCP
  extraMounts:
  - hostPath: E:\PodmanDrive
    containerPath: /data
- role: worker
  extraMounts:
  - hostPath: E:\PodmanDrive
    containerPath: /data